'use strict';
// Copies the already-built static site (the real tv-pro.app export) into desktop/site, and applies exactly one
// small, additive patch to the copied JS bundle: if the desktop app's local loopback gateway started
// successfully, prefer it first in the gateway list (see src/localProxy.js, src/preload.js). The root site files
// are never modified — this script only ever reads them and writes into desktop/site, which is build output
// (gitignored) and gets regenerated by this script before every dev run / package build.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.join(__dirname, '..', '..');
const SITE_OUT = path.join(__dirname, '..', 'site');

// What the desktop app actually needs to serve; sw.js is intentionally excluded (see README-ar.md: a service
// worker's app-shell caching is redundant, and a source of stale-bundle/white-screen bugs, in an app whose shell
// is already local), as are the gateway/CI-only files (cloudflare-worker.js, wrangler.toml, tests/, *.md).
const COPY_ENTRIES = ['index.html', 'manifest.webmanifest', 'favicon.ico', 'icons', '_next', 'diag.html', 'og-image.png'];

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copyRecursive(src, dst) { fs.cpSync(src, dst, { recursive: true }); }

function patchBundle() {
  const indexPath = path.join(SITE_OUT, 'index.html');
  let indexHtml = fs.readFileSync(indexPath, 'utf8');
  const m = indexHtml.match(/\/_next\/static\/chunks\/app\/(page-[a-f0-9]+\.js)/);
  if (!m) throw new Error('could not find the page-*.js bundle reference in index.html');
  const oldFile = m[1];
  const bundlePath = path.join(SITE_OUT, '_next', 'static', 'chunks', 'app', oldFile);
  let src = fs.readFileSync(bundlePath, 'utf8');

  const needle = 'function c(e){var t;return e.proxyUrlCustom?e.proxyUrl?[e.proxyUrl]:[]:[...new Set([l,...i].filter(e=>!!e))]}';
  const count = src.split(needle).length - 1;
  if (count !== 1) throw new Error(`expected exactly one match for the gateway-list patch point, found ${count} (upstream bundle changed shape — update scripts/build-site.js)`);
  const replacement =
    'function c(e){var t;if(e.proxyUrlCustom)return e.proxyUrl?[e.proxyUrl]:[];' +
    'let g="undefined"!=typeof window&&window.__tvproLocalGateway?[window.__tvproLocalGateway]:[];' +
    'return[...new Set([...g,l,...i].filter(e=>!!e))]}';
  src = src.replace(needle, replacement);

  const newFile = 'page-' + crypto.createHash('md5').update(src).digest('hex').slice(0, 16) + '.js';
  fs.writeFileSync(path.join(SITE_OUT, '_next', 'static', 'chunks', 'app', newFile), src);
  fs.rmSync(bundlePath);
  indexHtml = indexHtml.split(oldFile).join(newFile);
  fs.writeFileSync(indexPath, indexHtml);
  return { oldFile, newFile };
}

function main() {
  rmrf(SITE_OUT);
  fs.mkdirSync(SITE_OUT, { recursive: true });
  for (const entry of COPY_ENTRIES) {
    const src = path.join(ROOT, entry);
    if (!fs.existsSync(src)) { console.warn('skip (missing):', entry); continue; }
    copyRecursive(src, path.join(SITE_OUT, entry));
  }
  const { oldFile, newFile } = patchBundle();
  console.log('desktop/site built from the root export.');
  console.log(`gateway-list patch applied: ${oldFile} -> ${newFile}`);
}

main();
